language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
before_install:
  - pip install codecov
install:
  - make bin/pip
  - bin/pip install Twisted
  - make bin/tox
script:
  - bin/tox -e py
after_success:
  - codecov
